CREATE TABLE security.login
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_login PRIMARY KEY (id)
);

CREATE TABLE security.login_roles
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_id BIGINT                                  NOT NULL,
    role_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_login_roles PRIMARY KEY (id)
);

CREATE TABLE security.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE security.login
    ADD CONSTRAINT uc_c14c098c82a9f5647aa3c5491 UNIQUE (username);

ALTER TABLE security.login
    ADD CONSTRAINT uc_e19e039cac26a4f8aaa2699d1 UNIQUE (email);

ALTER TABLE security.login
    ADD CONSTRAINT uc_login_id UNIQUE (id);

ALTER TABLE security.login_roles
    ADD CONSTRAINT FK_LOGIN_ROLES_ON_LOGIN FOREIGN KEY (login_id) REFERENCES security.login (id);

ALTER TABLE security.login_roles
    ADD CONSTRAINT FK_LOGIN_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES security.role (id);