CREATE TABLE profiles.profile
(
    profile_id    BIGINT                   NOT NULL,
    username      VARCHAR(255)             NOT NULL,
    icon          SMALLINT                 NULL,
    creation_date TIMESTAMP with time zone NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (profile_id)
);

CREATE TABLE workspaces.chat
(
    chat_id  BIGINT NOT NULL,
    issue_id BIGINT,
    CONSTRAINT pk_chat PRIMARY KEY (chat_id)
);

CREATE TABLE workspaces.issue
(
    issue_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id    BIGINT,
    workspace_id  BIGINT,
    issue_name    VARCHAR(255)                            NOT NULL,
    creation_date TIMESTAMP with time zone                NOT NULL,
    deadline      TIMESTAMP with time zone,
    state         INTEGER                                 NOT NULL,
    CONSTRAINT pk_issue PRIMARY KEY (issue_id)
);

CREATE TABLE workspaces.message
(
    message_id    BIGINT                   NOT NULL,
    chat_id       BIGINT,
    profile_id    BIGINT,
    creation_date TIMESTAMP with time zone NOT NULL,
    content       VARCHAR(255)             NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (message_id)
);

CREATE TABLE workspaces.workspace
(
    workspace_id          BIGINT       NOT NULL,
    workspace_name        VARCHAR(255) NOT NULL,
    workspace_description VARCHAR(255),
    CONSTRAINT pk_workspace PRIMARY KEY (workspace_id)
);

CREATE TABLE workspaces.workspace_members
(
    workspace_members_id BIGINT  NOT NULL,
    profile_id           BIGINT,
    workspace_id         BIGINT,
    role                 INTEGER NOT NULL,
    CONSTRAINT pk_workspacemembers PRIMARY KEY (workspace_members_id)
);

ALTER TABLE profiles.profile
    ADD CONSTRAINT uc_profile_profileid UNIQUE (profile_id);

ALTER TABLE profiles.profile
    ADD CONSTRAINT uc_profile_username UNIQUE (username);

ALTER TABLE workspaces.chat
    ADD CONSTRAINT uc_chat_chatid UNIQUE (chat_id);

ALTER TABLE workspaces.issue
    ADD CONSTRAINT uc_issue_issue UNIQUE (issue_id);

ALTER TABLE workspaces.issue
    ADD CONSTRAINT uc_issue_issuename UNIQUE (issue_name);

ALTER TABLE workspaces.message
    ADD CONSTRAINT uc_message_messageid UNIQUE (message_id);

ALTER TABLE workspaces.workspace
    ADD CONSTRAINT uc_workspace_workspaceid UNIQUE (workspace_id);

ALTER TABLE workspaces.workspace
    ADD CONSTRAINT uc_workspace_workspacename UNIQUE (workspace_name);

ALTER TABLE workspaces.workspace_members
    ADD CONSTRAINT uc_workspacemembers_workspacemembersid UNIQUE (workspace_members_id);

ALTER TABLE workspaces.message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES workspaces.chat (chat_id);

ALTER TABLE workspaces.workspace_members
    ADD CONSTRAINT FK_WORKSPACEMEMBERS_ON_PROFILEID FOREIGN KEY (profile_id) REFERENCES profiles.profile (profile_id);

ALTER TABLE workspaces.workspace_members
    ADD CONSTRAINT FK_WORKSPACEMEMBERS_ON_WORKSPACE FOREIGN KEY (workspace_id) REFERENCES workspaces.workspace (workspace_id);